DROP TABLE IF EXISTS words;

CREATE TABLE words (
    word VARCHAR(50) PRIMARY KEY,
    comment VARCHAR(1000) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_review_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interval_days INT NOT NULL
);
